version: '3.7'

services:

  sample:
    container_name: react-datta
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 10104:10104
    environment:
      - CHOKIDAR_USEPOLLING=true
      